name: 'build, test, code coverage report'
description: 'composite actions'
runs:
  using: "composite"
  steps:
    - name: check out the code
      uses: actions/checkout@v3
    - name: Install the packages
      run: npm install
      shell: bash
    - name: Unit test
      run: npm run test
      shell: bash
    - name: Code coverage report
      run: npm run coverage
      shell: bash
