name: 'build, test, code coverage report'
description: 'composite actions'
inputs:
  unitTest:  # id of input
    description: 'run unit test'
    required: true
  codecoverage:  # id of input
    description: 'run code coverage'
    required: true

runs:
  using: "composite"
  steps:
    - name: check out the code
      uses: actions/checkout@v3
    - name: Install the packages
      run: npm install
      shell: bash
    - name: Unit testt
      run: | 
        unitTest=${{ inputs.unitTest }}
        if [[ "${unitTest}" == true ]]; then
          npm run test
        else
          echo "unit test skipped" 
        fi
      shell: bash
    - name: Code coverage report
      run: | 
        codecoverage=${{ inputs.codecoverage }}
        if [[ "${codecoverage}" == true ]]; then
          npm run coverage
        else
          echo "code coverage skipped"
        fi
      shell: bash
      

