name: 'build, test, code coverage report'
description: 'composite actions'

runs:
  using: "composite"
  steps:
    - run: npm install
      shell: bash
    - name: check out the code
      uses: actions/checkout@v3
    - run: npm run test
      shell: bash
    - run: npm run coverage
      shell: bash
