name: Basic github actions  

on:
  push:
    branches: [ master ]
  workflow_call:
    inputs:
      unit_test:
        required: true
        type: boolean
      code_coverage:
        required: true
        type: boolean

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: check out the code
      uses: actions/checkout@v3
    - name: Install the packages
      run: npm install
    - name: Unit test
      if: ${{github.event.inputs.unit_test}} == true
      run: npm run test
    - name: Code coverage report
      if: ${{ github.event.inputs.code_coverage }} == true
      run: npm run coverage
    - run: echo "hello ${{ github.event.inputs.unit_test }}""
