name: Print some text every 3rd minute
on:
  push:
    branches: [ master, main ]
  workflow_call:
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
    inputs:
      unit_test:
        description: 'unit test'
        required: true
        default: false
        type: boolean
      code_coverage:
        description: 'code coverage'
        required: true
        default: false
        type: boolean

jobs:
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Set the variables
        env:
          unit_test: false  
        run: echo "unittest=${{ github.event.inputs.unit_test || env.unit_test }}" >> $GITHUB_ENV
      - name: Print unit test
        run: echo "$unittest"
      - name: Set the variables
        env:
          code_coverage: false 
        run: echo "codecoverage=${{ github.event.inputs.code_coverage || env.code_coverage }}" >> $GITHUB_ENV
      - name: Print code coverage
        run: echo "$codecoverage"
      - name: check out the code
        uses: actions/checkout@v3
      - name: Install the packages
        run: npm install
      - name: Unit test
        if: $${{ github.event.inputs.unit_test }} == true
        run: npm run test
      - name: Code coverage report
        if: $${{ github.event.inputs.code_coverage }} == true
        run: npm run coverage
