name: node.js-workflow

on:
  workflow_dispatch:
    inputs:
      unit_test:
        description: 'unit test'
        default: ''
        required: true
      code_coverage:
        description: 'code coverage'
        default: ''
        required: true

jobs:

  node-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.unit_test }}"