name: Print some text every 3rd minute
on:
  push:
    branches: [ master, main ]
  workflow_call:
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
    inputs:
      text_to_print:
        description: 'What text do you want to print?'
        required: true
        default: 'Periodically printing passages'

jobs:
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Set the variables
        env:
          DEFAULT_MESSAGE: 'Periodically printing passages' # here is the default message
        run: echo "MESSAGE=${{ github.event.inputs.text_to_print || env.DEFAULT_MESSAGE }}" >> $GITHUB_ENV

      - name: Print some text
        run: echo ${{ github.event.inputs.text_to_print }} # prints the environmental variable, MESSAGE
