name: node.js-workflow

on:
  push:
    branches: [ master, main ]
  workflow_call:
    inputs:
      test:
        description: 'unit test'
        type: boolean
        required: true
      code_coverage:
        description: 'code coverage'
        type: boolean
        required: true

jobs:

  node-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.test }}"