name: Print some text every 3rd minute
on:
  push:
    branches: [ master, main ]
  workflow_call:
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
    inputs:
      unit_test:
        description: 'unit test'
        required: true
        default: false
        type: boolean
      code_coverage:
        description: 'code coverage'
        required: true
        default: false
        type: boolean

jobs:
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: check out the code
        uses: actions/checkout@v3
      - name: Install the packages
        run: npm install ${{ inputs.unit_test }} ${{ inputs.code_coverage }}
      - name: Unit test
        if: ${{ inputs.unit_test }} == true
        run: npm run test
      - name: Code coverage report
        if: ${{ inputs.unit_test }} == true
        run: npm run coverage
